site_name: SENTU.blog
theme:
  name: material

  favicon: img/favicon.png
  language: es
  icon:
    logo: fontawesome/solid/hat-cowboy
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest

  plugins:
    - typeset
    - search

  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to light mode

    #Palette toggle for light mode
    - scheme: default
      primary: green
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
#  - pymdownx.emoji:
#    emoji_index: !!python/name:material.extensions.emoji.twemoji
#    emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
    permalink: true

copyright: Copyright &copy; 2024 Luis Echenique
# extra_css:
#  - css/extra.css
extra:
  generator: false
  social:
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/elepistemedev