site_name: SENTUstudio
site_url: https://SENTUstudio.github.io/
site_author: Luis Echenique
site_title: "Impulsa tu negocio con data-driven insights: Soluciones de ingeniería de datos para empresas"
site_description: >-
  ¿Está buscando aprovechar al máximo sus datos para impulsar el crecimiento y la innovación de su negocio? En SENTU, ofrecemos soluciones de ingeniería de datos de vanguardia que le ayudarán a transformar sus datos en información valiosa que puede utilizar para tomar decisiones más inteligentes, mejorar la eficiencia operativa y obtener una ventaja competitiva.

# Repository
repo_name: SENTUstudio/web-blog
repo_url: https://github.com/SENTUstudio/SENTUstudio.github.io

theme:
  name: material
  custom_dir: material/overrides
  favicon: img/favicon.png
  language: es
  icon:
    logo: fontawesome/solid/feather
  features:
    - content.code.annotation
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
#    - toc.integrate

  plugins:
    - typeset
    - search:
        separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
    - minify:
        minify_html: true

  # Hooks
  hooks:
    - material/overrides/hooks/shortcodes.py
    - material/overrides/hooks/translations.py

  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Cambia al light mode

    #Palette toggle for light mode
    - scheme: default
      primary: amber
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Cambia al dark mode

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
#  - pymdownx.magiclink:
#      normalize_issue_symbols: true
#      repo_url_shorthand: true
#      user: squidfunk
#      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

copyright: Copyright &copy; 2024 Luis Echenique
# extra_css:
#  - css/extra.css
extra:
  generator: false
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/SENTUstudio
  - icon: fontawesome/brands/x-twitter
    link: https://x.com/squidfunk
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/in/echeniqueluis/